### ISSUE TITLE
What's about django 1.11 ;)

### ISSUE THREAD

**Issue by jedie** [kapt-labs/djangocms-htmlsitemap#4]
Is this project alive?

**Comment by adrien-delhorme** [comment]
Yes! The plugin is now compatible with Django 1.11.

**Comment by jedie** [comment]
When will a new release be available?

https://pypi.org/project/djangocms-htmlsitemap/#history lists only the old v0.2.0

**Comment by adrien-delhorme** [comment]
Now

**Comment by jedie** [comment]
Great!
