### ISSUE TITLE
Django-CMS 3.5 compatibility

### ISSUE THREAD

**Issue by wiesion** [kapt-labs/djangocms-htmlsitemap#6]
Will this plugin be made compatible with DjangoCMS 3.5 (and pushed to pypi)?

If i compare the release notes in http://docs.django-cms.org/en/latest/upgrade/3.5.html to your code, it seems there should be no problems, (only `django-reversion` in your sample project is not supported by DjangoCMS anymore).

**Comment by adrien-delhorme** [comment]
Version 0.4.0 compatible with DjangoCMS 3.5 pushed to Pypi, thanks to @jproffitt.
